-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE personals (
    Id SERIAL PRIMARY KEY,
    Title text NOT NULL UNIQUE,
    Forename text NOT NULL,
    Kadr text NOT NULL,
    Numotdel integer NOT NULL DEFAULT 1,
    Tarif integer NOT NULL DEFAULT 100,
    Email text NOT NULL UNIQUE,
    Phone text NOT NULL DEFAULT '8123456789'::text,
    Address text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX personals_pkey ON personals(Id int4_ops);
CREATE UNIQUE INDEX personals_title_key ON personals(Title text_ops);
CREATE UNIQUE INDEX personals_email_key ON personals(Email text_ops);
