-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE monds (
    Id SERIAL PRIMARY KEY,
    Yahre integer NOT NULL DEFAULT 2021,
    Nummonat integer NOT NULL,
    Tag integer NOT NULL DEFAULT 21,
    Hour integer NOT NULL DEFAULT 168,
    Kf integer NOT NULL DEFAULT 2,
    blmond integer NOT NULL DEFAULT 0,
    bltime text NOT NULL DEFAULT '0'::text,
    bltabel text NOT NULL DEFAULT '0'::text,
    blbuch text NOT NULL DEFAULT '0'::text,
    blpers text NOT NULL DEFAULT '0'::text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX monds_pkey ON monds(Id int4_ops);
Yahre