version: '3'
services:
  db:
    image: postgres:10.6-alpine
    ports:
      - '5432:5432'
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: geoplastdb
      POSTGRES_USER: yp
      POSTGRES_PASSWORD: 12345